version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nirnay
      POSTGRES_PASSWORD: nirnaypassword
      POSTGRES_DB: nirnayai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nirnay -d nirnayai"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MOBSF_API_KEY=mobsfapikey123
      - MOBSF_ANALYZER_IDENTIFIER=android-sandbox-1:5555
    volumes:
      - mobsfdata:/home/mobsf/.MobSF

  android-sandbox-1:
    image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:latest
    privileged: true
    shm_size: "2gb"
    devices:
      - /dev/kvm:/dev/kvm
    environment:
      - WEB_VNC=true
    ports:
      - "5555:5555"



  web:
    image: ghcr.io/harsh-devops117/nirnayai/web:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api-server

  api-server:
    image: ghcr.io/harsh-devops117/nirnayai/api-server:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://nirnay:nirnaypassword@postgres:5432/nirnayai?schema=public
      - REDIS_URL=redis://redis:6379
    volumes:
      - uploadsdata:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    image: ghcr.io/harsh-devops117/nirnayai/worker:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://nirnay:nirnaypassword@postgres:5432/nirnayai?schema=public
      - REDIS_URL=redis://redis:6379
      - MOBSF_URL=http://mobsf:8000
    volumes:
      - uploadsdata:/app/uploads
    depends_on:
      - redis
      - mobsf

  whatsapp-bot:
    image: ghcr.io/harsh-devops117/nirnayai/whatsapp-bot:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/whatsapp/Dockerfile
    env_file:
      - .env
    environment:
      - API_URL=http://api-server:3000/api/v1
      - DATABASE_URL=postgresql://nirnay:nirnaypassword@postgres:5432/nirnayai?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - api-server
    volumes:
      - whatsappdata:/app/auth_info_baileys

volumes:
  pgdata:
  redisdata:
  mobsfdata:
  uploadsdata:
  whatsappdata:
